#!/usr/bin/env python3
#
# MyDisplays — geometry helpers for monitor layout overlap resolution
# Copyright (C) 2026 unobbb-bit <unobbb@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Pure geometry helpers for monitor layout overlap resolution.

No GTK, no Hyprland — pure math over monitor dicts of the shape:
    {"name": str, "width": int, "height": int, "scale": float, "x": int, "y": int}

Monitor coordinates are in *logical* (scale-divided) pixels, matching
what Hyprland uses in its monitor layout. Every function here works for
any number of monitors.
"""


def monitor_rect(m):
    """Return the logical rect (x, y, w, h) of a monitor."""
    return (m["x"], m["y"], m["width"] / m["scale"], m["height"] / m["scale"])


def rects_overlap(a, b):
    """True if rect a overlaps rect b. Touching edges do not overlap."""
    ax, ay, aw, ah = a
    bx, by, bw, bh = b
    return ax < bx + bw and ax + aw > bx and ay < by + bh and ay + ah > by


def rect_overlaps_any(rect, monitors):
    """True if rect overlaps any monitor in the list."""
    for other in monitors:
        if rects_overlap(rect, monitor_rect(other)):
            return True
    return False


def clamp_position(monitors, m, new_x, new_y):
    """Return (x, y) closest to (new_x, new_y) that does not overlap anything.

    If the requested position is already free it is returned unchanged.
    Otherwise a best-first search expands the pushed positions generated by
    each overlapping monitor's four edges and returns the nearest valid spot.
    All pushes are done in integer space (ceil when pushing right/down, floor
    when pushing left/up) so the result is always overlap-free. Works for any N.
    """
    import heapq
    import math

    m_w = m["width"] / m["scale"]
    m_h = m["height"] / m["scale"]
    others = [o for o in monitors if o is not m and o.get("name") != m.get("name")]

    start = (round(new_x), round(new_y))
    if not rect_overlaps_any((start[0], start[1], m_w, m_h), others):
        return start

    target = (float(new_x), float(new_y))
    frontier = []

    def dist2(x, y):
        return (x - target[0]) ** 2 + (y - target[1]) ** 2

    heapq.heappush(frontier, (dist2(*start), start[0], start[1]))
    seen = {start}

    while frontier:
        _, cx, cy = heapq.heappop(frontier)
        for other in others:
            ox, oy, ow, oh = monitor_rect(other)
            if not rects_overlap((cx, cy, m_w, m_h), (ox, oy, ow, oh)):
                continue
            candidates = (
                (math.ceil(ox + ow), cy),          # push right of other
                (math.floor(ox - m_w), cy),        # push left of other
                (cx, math.ceil(oy + oh)),          # push below other
                (cx, math.floor(oy - m_h)),        # push above other
            )
            for cand in candidates:
                if cand in seen:
                    continue
                seen.add(cand)
                if not rect_overlaps_any((cand[0], cand[1], m_w, m_h), others):
                    return cand
                heapq.heappush(frontier, (dist2(*cand), cand[0], cand[1]))
        if len(seen) > 10000:
            break

    # Unreachable in practice, but guarantee a valid spot: right of everything.
    max_right = max(monitor_rect(o)[0] + monitor_rect(o)[2] for o in others)
    return math.ceil(max_right) + 1, start[1]


def monitors_overlap(monitors):
    """True if any pair of monitors overlaps."""
    for i, a in enumerate(monitors):
        for b in monitors[i + 1:]:
            if rects_overlap(monitor_rect(a), monitor_rect(b)):
                return True
    return False


def snap_monitors(monitors):
    """Reposition overlapping monitors so the whole layout is overlap-free.

    Iteratively pushes every overlapping monitor to its nearest free position.
    Monitors that are already well placed are never moved. Works for any N.
    Returns True if any monitor was moved.
    """
    moved_any = False
    for _ in range(monitors.__len__() * 2 + 4):
        moved = False
        for m in monitors:
            others = [o for o in monitors if o is not m]
            if rect_overlaps_any(monitor_rect(m), others):
                nx, ny = clamp_position(monitors, m, m["x"], m["y"])
                if (nx, ny) != (m["x"], m["y"]):
                    m["x"], m["y"] = nx, ny
                    moved = True
        if moved:
            moved_any = True
        else:
            break
    return moved_any
